#!/bin/bash

if [ "$1" == "adv" ] ; then
  /usr/bin/apt-key.cont adv --keyserver-options http-proxy="http://@@HTTP_PROXY_HOST:@@HTTP_PROXY_PORT/" "$2 $3 $4 $5 $6 $7 $8 $9"
else
  /usr/bin/apt-key.cont "$@"
fi
